version: 2

jobs:
  linux:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux-vapor:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - run:
          name: Clone Vapor
          command: git clone -b 4 https://github.com/vapor/vapor.git
          working_directory: ~/
      - run:
          name: Switch Vapor to this Routing revision
          command: swift package edit RoutingKit --revision $CIRCLE_SHA1
          working_directory: ~/vapor
      - run:
          name: Run Vapor unit tests
          command: swift test
          working_directory: ~/vapor

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-vapor
      
