version: 2

jobs:
  linux:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
    tests:
      jobs:
        - linux
      
