version: 2

jobs:
  version: 2

jobs:
  linux-performance:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run:
          name: swift test
          command: swift test -c release --filter "RoutingKitTests.RouterPerformanceTests"

workflows:
  version: 2

notify:
  webhooks:
    - url: https://bot-gh.vapor.codes/circle/result
