version: 2

jobs:
  linux:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run: swift build
      - run:
          name: swift test
          command: swift test --filter "RoutingKitTests.RouterTests"
  linux-release:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run: swift build -c release
  linux-performance:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run:
          name: swift test
          command: swift test -c release --filter "RoutingKitTests.RouterPerformanceTests"

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
notify:
  webhooks:
    - url: https://bot-gh.vapor.codes/circle
